#!/bin/sh -x

export ANDROID_MAJOR_VERSION=q
export CROSS_COMPILE=../toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-

make mrproper
make ARCH=arm64 exynos9830-c2sxxx_caliban_defconfig
make ARCH=arm64 -j$(nproc)
